version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - wordpress
    volumes:
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx
  wordpress:
    build: ./wordpress
    depends_on:
      - mariadb
    volumes:
      - ./src:/var/www/html
      - ./logs/wordpress/php:/var/log/php
  mariadb:
    build: ./mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example
    volumes:
      - ./resources/mariadb:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql

        #phpmyadmin:
        #  image: phpmyadmin/phpmyadmin:latest
        #  environment:
        #    PMA_ARBITRARY: 1
        #    PMA_USER: root
        #    PMA_PASSWORD: example
        #  # 8080 ポートをコンテナの 80 ポートにマッピング
        #  # (http://localhost:8080/ などで myapp-pma コンテナにアクセス)
        #  ports:
        #    - 8000:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=wordpress
      - PMA_PASSWORD=example
    links:
      - mariadb
    ports:
      - 8000:80
        #volumes:
        #- /sessions
